<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * One scheduled administration: a (date, slot) for a dose item, and whether it
 * was given. Generated by DosageScheduleGenerator; marked by nursing staff.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('dose_item_records', function (Blueprint $table) {
            $table->id();
            $table->foreignId('hospital_id')->constrained()->cascadeOnDelete();
            $table->foreignId('dose_item_id')->constrained()->cascadeOnDelete();

            $table->date('scheduled_date');
            $table->string('slot', 12);                     // morning|afternoon|evening|night
            $table->string('status', 12)->default('pending');
            $table->dateTime('administered_at')->nullable();
            $table->foreignId('administered_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('note')->nullable();
            $table->timestamps();

            $table->unique(['dose_item_id', 'scheduled_date', 'slot'], 'dose_record_unique');
            $table->index(['hospital_id', 'scheduled_date', 'status'], 'dose_record_day');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('dose_item_records');
    }
};
